FIND_PATH(LIBZ_INCLUDE_DIR NAMES zlib.h)
FIND_LIBRARY(LIBZ_LIBRARIES NAMES z)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibZ DEFAULT_MSG LIBZ_LIBRARIES LIBZ_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBZ_INCLUDE_DIR LIBZ_LIBRARIES)
