# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mthomas/morphine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mthomas/morphine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mthomas/morphine/CMakeFiles /home/mthomas/morphine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mthomas/morphine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libmorphine

# Build rule for target.
libmorphine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmorphine
.PHONY : libmorphine

# fast build rule for target.
libmorphine/fast:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/build
.PHONY : libmorphine/fast

#=============================================================================
# Target rules for targets named maps

# Build rule for target.
maps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maps
.PHONY : maps

# fast build rule for target.
maps/fast:
	$(MAKE) -f CMakeFiles/maps.dir/build.make CMakeFiles/maps.dir/build
.PHONY : maps/fast

examples/maps.o: examples/maps.c.o
.PHONY : examples/maps.o

# target to build an object file
examples/maps.c.o:
	$(MAKE) -f CMakeFiles/maps.dir/build.make CMakeFiles/maps.dir/examples/maps.c.o
.PHONY : examples/maps.c.o

examples/maps.i: examples/maps.c.i
.PHONY : examples/maps.i

# target to preprocess a source file
examples/maps.c.i:
	$(MAKE) -f CMakeFiles/maps.dir/build.make CMakeFiles/maps.dir/examples/maps.c.i
.PHONY : examples/maps.c.i

examples/maps.s: examples/maps.c.s
.PHONY : examples/maps.s

# target to generate assembly for a file
examples/maps.c.s:
	$(MAKE) -f CMakeFiles/maps.dir/build.make CMakeFiles/maps.dir/examples/maps.c.s
.PHONY : examples/maps.c.s

morph/json.o: morph/json.c.o
.PHONY : morph/json.o

# target to build an object file
morph/json.c.o:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/json.c.o
.PHONY : morph/json.c.o

morph/json.i: morph/json.c.i
.PHONY : morph/json.i

# target to preprocess a source file
morph/json.c.i:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/json.c.i
.PHONY : morph/json.c.i

morph/json.s: morph/json.c.s
.PHONY : morph/json.s

# target to generate assembly for a file
morph/json.c.s:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/json.c.s
.PHONY : morph/json.c.s

morph/lua.o: morph/lua.c.o
.PHONY : morph/lua.o

# target to build an object file
morph/lua.c.o:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/lua.c.o
.PHONY : morph/lua.c.o

morph/lua.i: morph/lua.c.i
.PHONY : morph/lua.i

# target to preprocess a source file
morph/lua.c.i:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/lua.c.i
.PHONY : morph/lua.c.i

morph/lua.s: morph/lua.c.s
.PHONY : morph/lua.s

# target to generate assembly for a file
morph/lua.c.s:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/lua.c.s
.PHONY : morph/lua.c.s

morph/stdout.o: morph/stdout.c.o
.PHONY : morph/stdout.o

# target to build an object file
morph/stdout.c.o:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/stdout.c.o
.PHONY : morph/stdout.c.o

morph/stdout.i: morph/stdout.c.i
.PHONY : morph/stdout.i

# target to preprocess a source file
morph/stdout.c.i:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/stdout.c.i
.PHONY : morph/stdout.c.i

morph/stdout.s: morph/stdout.c.s
.PHONY : morph/stdout.s

# target to generate assembly for a file
morph/stdout.c.s:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morph/stdout.c.s
.PHONY : morph/stdout.c.s

morphine.o: morphine.c.o
.PHONY : morphine.o

# target to build an object file
morphine.c.o:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morphine.c.o
.PHONY : morphine.c.o

morphine.i: morphine.c.i
.PHONY : morphine.i

# target to preprocess a source file
morphine.c.i:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morphine.c.i
.PHONY : morphine.c.i

morphine.s: morphine.c.s
.PHONY : morphine.s

# target to generate assembly for a file
morphine.c.s:
	$(MAKE) -f CMakeFiles/libmorphine.dir/build.make CMakeFiles/libmorphine.dir/morphine.c.s
.PHONY : morphine.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... libmorphine"
	@echo "... maps"
	@echo "... rebuild_cache"
	@echo "... examples/maps.o"
	@echo "... examples/maps.i"
	@echo "... examples/maps.s"
	@echo "... morph/json.o"
	@echo "... morph/json.i"
	@echo "... morph/json.s"
	@echo "... morph/lua.o"
	@echo "... morph/lua.i"
	@echo "... morph/lua.s"
	@echo "... morph/stdout.o"
	@echo "... morph/stdout.i"
	@echo "... morph/stdout.s"
	@echo "... morphine.o"
	@echo "... morphine.i"
	@echo "... morphine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

